// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt6ys_GMRYU4I-jV01aTeRaNM_383EIZo',
    appId: '1:248350173499:web:bbb48caddaa379c3bb6f1e',
    messagingSenderId: '248350173499',
    projectId: 'exam-planner-e76c9',
    authDomain: 'exam-planner-e76c9.firebaseapp.com',
    storageBucket: 'exam-planner-e76c9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTjrYmrRBOSKumrw9WiVsZAUQF80u7sww',
    appId: '1:248350173499:android:f6cfdacf97cc6ff1bb6f1e',
    messagingSenderId: '248350173499',
    projectId: 'exam-planner-e76c9',
    storageBucket: 'exam-planner-e76c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7zjCWdJvZNDR_-ySIemGbTzE50hw_fLE',
    appId: '1:248350173499:ios:4b17c7b4b6a2057bbb6f1e',
    messagingSenderId: '248350173499',
    projectId: 'exam-planner-e76c9',
    storageBucket: 'exam-planner-e76c9.appspot.com',
    iosBundleId: 'com.example.examPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7zjCWdJvZNDR_-ySIemGbTzE50hw_fLE',
    appId: '1:248350173499:ios:26bc34f027e207a1bb6f1e',
    messagingSenderId: '248350173499',
    projectId: 'exam-planner-e76c9',
    storageBucket: 'exam-planner-e76c9.appspot.com',
    iosBundleId: 'com.example.examPlanner.RunnerTests',
  );
}
